# Generated by Django 2.1.5 on 2019-09-13 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_historicaluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('changed_from', models.CharField(max_length=255)),
                ('changed_to', models.CharField(max_length=255)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_audited', to=settings.AUTH_USER_MODEL)),
                ('request_or_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='history_user',
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_noted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
