# Generated by Django 2.1.5 on 2019-09-13 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190913_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userauditlog',
            options={'verbose_name': 'Audit log', 'verbose_name_plural': 'Audit logs'},
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
