# Generated by Django 2.1.5 on 2019-09-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190913_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauditlog',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='userauditlog',
            name='request_or_user',
        ),
        migrations.DeleteModel(
            name='UserAuditLog',
        ),
    ]
