# Generated by Django 2.1.5 on 2019-09-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='request_or_user',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
