# Generated by Django 2.1.5 on 2019-07-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190718_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='1990-01-01', verbose_name='fødselsdag'),
        ),
    ]
