# Generated by Django 2.1.5 on 2019-07-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190719_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acquisition_source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Opprettet gjennom'),
        ),
    ]
