# Generated by Django 2.1.5 on 2019-08-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
