# Generated by Django 2.1.5 on 2019-08-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_historicaluser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
