# Generated by Django 2.1.5 on 2019-08-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20190811_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disabled_emails',
            field=models.BooleanField(default=False),
        ),
    ]
