# Generated by Django 3.0.1 on 2019-12-25 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='change time')),
                ('object_id', models.TextField(blank=True, null=True, verbose_name='object id')),
                ('object_representation', models.CharField(max_length=200, verbose_name='object representation')),
                ('action_flag', models.PositiveSmallIntegerField(choices=[(1, 'Addiotion'), (2, 'Change'), (3, 'Deletion')], verbose_name='action flag')),
                ('change_message', models.TextField(blank=True, verbose_name='change message')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='content type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_changed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Change log entry',
                'verbose_name_plural': 'Change log entries',
            },
        ),
    ]
