# Generated by Django 3.0.1 on 2019-12-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_changelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeLog',
        ),
    ]
